- name: Add Jenkins key
  get_url:
    url:  "{{ jenkins_repo_url }}"
    dest: /usr/share/keyrings/jenkins-keyring.asc
  register: jenkins_key

- name: Touch a file
  file:
    path: /etc/apt/sources.list.d/jenkins.list
    state: touch

- name: Add Jenkins repository
  shell: echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian binary/ | sudo tee /etc/apt/sources.list.d/jenkins.list > /dev/null
  when: jenkins_key.changed

- name: Apt update
  apt: 
    update_cache: true

- name: Apt install
  apt:
    name: "{{apt_install}}"

- name: Install jenkins 
  apt:
    name: jenkins

- name: Set permissions for /var/run/docker.sock
  file:
    path: /var/run/docker.sock
    mode: "0666"

- name: Install Jenkins Plugin Installation Manager
  get_url:
    url: https://github.com/jenkinsci/plugin-installation-manager-tool/releases/download/2.12.11/jenkins-plugin-manager-2.12.11.jar
    dest: /opt/

- name: Copy plugins.txt file 
  copy:
    src: plugins.txt
    dest: /opt/plugins.txt
    
- name: install jenkins plugins
  shell: java -jar /opt/jenkins-plugin-manager-*.jar --war /usr/share/java/jenkins.war -d /var/lib/jenkins/plugins -f /opt/plugins.txt

- name: restart Jenkins service
  service:
    state: restarted
    name: jenkins.service 
    enabled: true
    
- name: install helm
  shell: snap install helm --classic --channel=3.7/stable 

- name: Install kubectl snap package
  command: snap install kubectl --classic --channel=1.23/stable

- name: Get IP address of Nexus server
  set_fact:
    nexus_ip: "{{ hostvars['nexus_server']['ansible_host'] }}"

- name: Create daemon.json file
  file:
    path: /etc/docker/daemon.json
    state: touch

- name: Allow access to Nexus Docker repo
  lineinfile:
    dest: /etc/docker/daemon.json
    line: "{{ item }}"
  loop:
  - '{' 
  - '"insecure-registries":["{{ nexus_ip }}:{{ nexus_docker_port }}"]'
  - '}'

- name: restart Docker service
  service:
    state: restarted
    name: docker.service 
    enabled: true


- name: Set permissions on /var/lib/docker.socket
  file:
    path: /var/run/docker.sock
    mode: '0666'