- name: Add Jenkins key
  get_url:
    url:  "{{ jenkins_repo_url }}"
    dest: /usr/share/keyrings/jenkins-keyring.asc
  register: jenkins_key

- name: Touch a file
  file:
    path: /etc/apt/sources.list.d/jenkins.list
    state: touch

- name: Add Jenkins repository
  shell: echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian binary/ | sudo tee /etc/apt/sources.list.d/jenkins.list > /dev/null
  when: jenkins_key.changed

- name: Apt update
  apt: 
    update_cache: true

- name: Apt install
  apt:
    name: "{{apt_install}}"

- name: Install jenkins 
  apt:
    name: jenkins

- name: Set permissions for /var/run/docker.sock
  file:
    path: /var/run/docker.sock
    mode: "0666"

- name: Install Jenkins Plugin Installation Manager
  get_url:
    url: https://github.com/jenkinsci/plugin-installation-manager-tool/releases/download/2.12.11/jenkins-plugin-manager-2.12.11.jar
    dest: /opt/

- name: Copy plugins.txt file 
  copy:
    src: plugins.txt
    dest: /opt/plugins.txt
    
- name: install jenkins plugins
  shell: java -jar /opt/jenkins-plugin-manager-*.jar --war /usr/share/java/jenkins.war -d /var/lib/jenkins/plugins -f /opt/plugins.txt

- name: restart the service
  service:
    state: restarted
    name: jenkins.service 
    enabled: true
    
- name: install helm
  shell: snap install helm --classic