apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app_ingress
  labels:
    name: java_app
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: java_app_service
            port: 
              number: 8080
