- name: install openjdk
  apt:
    name: [openjdk-11-jdk,unzip]

- name: Unzip and download sonarqube
  unarchive:
    src: "https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-{{ sonarqube_version }}.zip"
    dest: /opt
    remote_src: true

- name: change name to sonarqube
  copy:
    src: "/opt/sonarqube-{{ sonarqube_version }}/"
    dest: /opt/sonarqube
    remote_src: true

- name: Create a sonar user and set /opt/sonarqube as the home directory
  user:
    name: sonar
    home: /opt/sonarqube

- name: Grant the sonar user access to the /opt/sonarqube directory
  file:
    dest: /opt/sonarqube
    owner: sonar
    group: sonar
    recurse: yes

- name: Edit the SonarQube configuration file part2
  lineinfile:
    dest: /opt/sonarqube/conf/sonar.properties
    line: "{{ item }}"
  loop: 
    - sonar.jdbc.username=sonar
    - sonar.jdbc.password="{{ sonar_password }}"
    - sonar.jdbc.url=jdbc:postgresql://localhost/sonarqube
    - sonar.search.javaOpts=-Xmx512m -Xms512m -XX:MaxDirectMemorySize=256m -XX:+HeapDumpOnOutOfMemoryError

- name: copy service file
  copy:
    src: sonarqube.service 
    dest: /etc/systemd/system/

- name: restart the service
  service:
    state: started
    name: sonarqube.service 
    enabled: true



